blog_on_rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  root({ to: 'posts#index'})
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

blog_on_rails/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, Post do |post|
      user == post.user
    end
    can :destroy, Comment do |comment|
      user == comment.post.user
    end
    can :manage, Comment do |comment|
      user == comment.user
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

blog_on_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog_on_rails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence:true
end

blog_on_rails/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  
  validates :title, presence:true, uniqueness: { message: 'That title already exists'}
  validates :body, presence:true, length: { minimum: 50 }
end

blog_on_rails/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: VALID_EMAIL_REGEX, uniqueness: true
  
  before_save :titleize_name 
  def titleize_name
    self.first_name = self.first_name.titleize if self.first_name
    self.last_name = self.last_name.titleize if self.last_name
  end
end

blog_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user #only if views will use this method

  def authenticate_user!
    unless current_user
      flash[:alert] = "Please sign in"
      redirect_to new_session_path
    end
  end
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

end

blog_on_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user
    
    if @comment.save
      redirect_to post_path(@post)
    else
      @comment = @post.comments.order(created_at: :desc)
      render "posts/show"
    end
  end

  def destroy
    @comment = Comment.find params[:id]
    authorize! :destroy, @comment
    @comment.destroy

    redirect_to post_path(@comment.post.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

blog_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order(id: :desc)
  end
  def show
    @post = Post.find params[:id]
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end
  def create
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find params[:id]
    authorize! :destroy, @post
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @post = Post.find params[:id]
    authorize! :edit, @post
  end
  def update
    @post = Post.find params[:id]
    authorize! :update, @post

    if @post.update post_params
      redirect_to post_path(@post.id)
    else
      render :edit
    end

  end



  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

blog_on_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else 
      @user ||= User.new
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = "Thank you for blogging"
    redirect_to new_session_path
  end

  private
  def user_params
    params
      .require(:user)
      .permit(:password, :email)
  end

end

blog_on_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params
      .require(:user)
      .permit(:first_name, :last_name, :password, :password_confirmation, :email)
  end
end

blog_on_rails/app/helpers/application_helper.rb
module ApplicationHelper

end

blog_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">
          <img src="/assets/blog.png" style="width: 20px">
        </a>
        <% if current_user %>
          <span class="mr-auto">Hello <%= current_user.first_name %></span>
          <%= link_to "Sign-Out", session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign-Up", new_user_path %>
          <%= link_to "Sign-In", new_session_path %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Posts
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "All Posts", posts_path, class: "dropdown-item" %>
                <%= link_to "New Post", new_post_path, class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong> <%= message %> </strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

blog_on_rails/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.present? %>
    <% @post.errors.full_messages.each do |m| %>
      <div class="alert alert-warning" role="alert"><%= m %></div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :body, size: "60x12", class: "form-control" %>
  </div>
  <%= f.submit "Save", class: "btn btn-dark" %>
<% end %>

blog_on_rails/app/views/posts/edit.html.erb
<div class="w-50">
  <h1>Edit Post</h1>

  <%= render "form" %>
</div>

blog_on_rails/app/views/posts/index.html.erb
<div class="w-50">
  <h1>All the posts</h1>

  <ul>
    <% @posts.each do |post| %>
      <li> <%= link_to(post.title, post_path(post.id), class: "$link-color") %></li>
    <% end %>
  </ul>
</div>

blog_on_rails/app/views/posts/new.html.erb
<div class="w-50">
  <h1>New Post</h1>
    
    <%= render "form" %>
</div>

blog_on_rails/app/views/posts/show.html.erb
<div class="border border-dark rounded p-3 w-50">
  <div>
    <h3><%= @post.title %></h1>
  </div>
  <div>
    <p><%= @post.body %></p>
  </div>
  <div class="d-flex">
    <small class="ml-auto">
    Created <%= distance_of_time_in_words(Time.now, @post.created_at) %> ago
    </small>
  </div>

  <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to(
      "Edit",
      edit_post_path(@post.id),
      class: "btn btn-sm btn-secondary"
    ) %>
    <%= link_to(
      "Delete",
      post_path(@post.id),
      method: :delete,
      data: { confirm: "This post will be gone forever" },
      class: "btn btn-sm btn-outline-secondary") %>
  </div>
  <div class="m-3">
    <%= form_for ([@post, @comment]) do |f| %>
      <% if @comment.errors.present? %>
        <% @post.errors.full_messages.each do |m| %>
          <div class="alert alert-warning" role="alert"><%= m %></div>
        <% end %>
      <% end %>
      <div class="form-group">
        <%= f.text_area :body, size: "60x3", class: "form-control" %>
      </div>
      <%= f.submit "Comment", class: "btn btn-sm btn-outline-dark" %>
    <% end %>
  </div>
  <div>
    <h4>Comments:</h4>
    <ul>
      <% @comments.each do |comment| %>
        <li><%= comment.body %>
          <small>- <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago - 
          <%= link_to(
            "Delete",
            post_comment_path(@post, comment),
            method: :delete,
            data: { confirm: "Bye bye comment?" }) %>
          </small>
        </li>
      <% end %>
    </ul>
  </div>
</div>

blog_on_rails/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.present? %>
    <% @user.errors.full_messages.each do |m| %>
      <div class="alert alert-warning" role="alert"><%= m %></div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
    <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-dark" %>
<% end %>